;;PrintTwoReduced Simpler version using partCombine                
(let ((id #f)(tag "Share Staff" )(stems-swapped #f)(upstart 0)(downstart 0)(up 0)(down 0)(o1 1)(o2 1) (m 1) (bar 1)(s1 1)(s2 2)) 
(set! id (d-GetIdForName tag))
(d-DirectivePut-scoreheader-postfix tag "\ninstrumentation=\"Accompanist's Score\"\n")

(while (<= m (d-GetMovementsInScore))
    (set! s1 1)
    (set! s2 2)
    (set! bar 1)
   
    (set! o1 1)
    (set! o2 1)
    
    (d-GoToPosition m s1 bar o1)
    (d-SmallerStaff)
    (d-DirectivePut-staff-prefix tag "instrumentName = \\markup Soli")
    (d-DirectivePut-staff-override tag  (logior DENEMO_ALT_OVERRIDE  DENEMO_OVERRIDE_AFFIX  DENEMO_OVERRIDE_GRAPHIC))
    (d-DirectivePut-standalone tag)
    (d-DirectivePut-standalone-minpixels tag 5)
    (d-DirectivePut-standalone-postfix tag "\\omit Staff.Slur \\omit Staff.Tie ")
    (d-DirectivePut-standalone-allow tag id)
    (d-GoToPosition m s2 bar o2)
    (d-SmallerStaff)
    (d-SetCurrentStaffAsVoice)
    (d-PartCombine tag)
    (set! m (1+ m)))
(d-CreateLayout tag)  
(d-SelectDefaultLayout)
(d-DirectiveDelete-scoreheader tag)
(set! m 1) 
(while (<= m (d-GetMovementsInScore))
    (d-GoToPosition m s1 1 1)
    (d-SmallerStaff)
    (d-DirectiveDelete-staff tag)
    (d-GoToPosition m s2 1 1) 
    ;(disp "Restoring voice as staff in movement " m "\n")
    (d-SetCurrentVoiceAsStaff)
    (d-SmallerStaff) ;;deletes the smaller staff directive as it is fixed in the ShareStaff layout
    (set! m (1+ m)))
(d-GoToPosition 1 1 1 1)
(d-SelectLayoutId id)
(d-SetSaved #f))