;;;PrintBassWithoutFigures
(let ((saved (d-GetSaved)) (name "Unfigured Bass Part"))
    (define (do-staff)
       (d-ShowFiguredBass)
        (if (d-HasFigures)
            (d-HideFiguredBass)
            (d-NonPrintingStaff)))
    (define (undo-staff)
       (d-ShowFiguredBass)
        (if (d-HasFigures)
            (d-ShowFiguredBass)
            (d-NonPrintingStaff)))
    (ForAllMovements "(ForAllStaffs \"(do-staff)\")")
    (d-CreateLayout name))
    (ForAllMovements "(ForAllStaffs \"(undo-staff)\")"))
