(let ((tag "TerminateHairpinAtBarline"))
(d-MoveCursorRight)
(d-Directive-standalone tag)
(d-DirectivePut-standalone-postfix tag "<>\\!  ")
(d-DirectivePut-standalone-display tag "<>\\!  ")
(d-DirectivePut-standalone-minpixels tag 30)
(d-SetSaved #f)
(d-RefreshDisplay))
