;;;GenerateMusicSignatureSearchScript
(d-GoToPosition 1 1 1 1)
(let ((current (d-GetNoteFromTopAsMidi))
        (port (open-file "denemo_search.sh" "w"))
        (steps "find . -name \"*.denemo*\" -exec denemo -a \"(define DenemoMusicSignature '(")
        (count (string->number (d-GetUserInput "Create Music Signature" "Give number of notes to match: " "5")))
        (test #f)
        (next #f))
    (if (not current)
        (d-NextNote))
    (set! current (d-GetNoteFromTopAsMidi))

    (while (and (d-NextNote) (> count 0))
        (set! next (d-GetNoteFromTopAsMidi))
        (set! test (- next current))
        (set! steps (string-append steps " " (number->string test)))
        (set! current next)
        (set! count (1- count)))
    (set! steps (string-append steps "))\" -n -i " DENEMO_ACTIONS_DIR "checkMusicSignature.scm '{}' \\;  2>/dev/null | grep 𝅘𝅥 "))
    (format port "~A " steps)
    (close-port port)
    (d-InfoDialog "The bash script denemo-search.sh will search\nfor files starting with the same intervals."))
