;;AllowAmbitus
(let ((tag "Ambitus")(criterion (_ "Ambitus")))
    (define (doAmbitus)
      (while (d-PreviousMovement))
      (let movement ()
		(while (d-MoveToStaffUp))
		(let staff ()
		  ;;skip voices? mirrored staffs?
			 (d-DirectivePut-staff-prefix tag "\\consists \"Ambitus_engraver\"\n")
			 (d-DirectivePut-staff-override tag  (logior DENEMO_ALT_OVERRIDE  DENEMO_OVERRIDE_AFFIX  DENEMO_OVERRIDE_GRAPHIC))
			 (d-DirectivePut-staff-ignore tag (cdr (d-GetIncludeCriterion)))
			 (if (or (d-MoveToVoiceDown) (d-MoveToStaffDown))
				(staff)))
	    (if (d-NextMovement)
		(movement))))
     (d-PushPosition)
	 (let ((saved (d-GetSaved)))
		(d-CreateIncludeCriterion criterion)
		(d-SetIncludeCriterion criterion)
		(doAmbitus)
		(d-SetSaved saved))
    (d-PopPosition))