;;;ToggleDisplayAllStaffs
(let ((params ToggleDisplayAllStaffs::params))
	(if (d-StaffHidden)
		(begin
			(d-PushPosition)
			(while (d-MoveToStaffUp))
			(d-StaffHidden #f)
			(while (d-MoveToStaffDown)
				(d-StaffHidden #f))
			(d-PopPosition))
		(let ((hide #t))
			(d-PushPosition)
			(while (d-MoveToStaffUp)
				(if (d-StaffHidden)
					(set! hide #f)))
			(d-PopPosition)
			(d-PushPosition)
			(while (d-MoveToStaffDown)
				(if (d-StaffHidden)
					(set! hide #f))) ;; hide is now #f if there are other hidden staffs
			(d-GoToPosition #f 1 1 1)
			(d-StaffHidden hide)
			(while (d-MoveToStaffDown)
				(d-StaffHidden hide))
			(d-PopPosition)
			(d-StaffHidden #f))))
