(define IntervalComparison::Mi2 (cons "Mi2" "c des"))
(define IntervalComparison::Ma2 (cons "Ma2" "c d"))
(define IntervalComparison::Mi3 (cons "Mi3" "c ees"))
(define IntervalComparison::Ma3 (cons "Ma3" "c e"))
(define IntervalComparison::P4 (cons "P4" "c f"))
(define IntervalComparison::D5 (cons "D5" "c ges"))
(define IntervalComparison::P5 (cons "P5" "c g"))
(define IntervalComparison::Mi6 (cons "Mi6" "c aes"))
(define IntervalComparison::Ma6 (cons "Ma6" "c a"))
(define IntervalComparison::Mi7 (cons "Mi7" "c bes"))
(define IntervalComparison::Ma7 (cons "Ma7" "c b"))
(define IntervalComparison::P8 (cons "P8" "c c'"))

(IntervalComparison::IntervalComparison (list IntervalComparison::Mi2 IntervalComparison::Ma2 IntervalComparison::Mi3 IntervalComparison::Ma3 IntervalComparison::P4 IntervalComparison::D5 IntervalComparison::P5 IntervalComparison::Mi6 IntervalComparison::Ma6 IntervalComparison::Mi7 IntervalComparison::Ma7 IntervalComparison::P8))

