(d-DirectiveDelete-staff "GroupStaffStart")
(d-DirectiveDelete-staff "PianoStaffStart")
(d-DirectiveDelete-staff "ChoirStaffStart")
(d-DirectiveDelete-staff "GrandStaffStart")
(while (d-DirectiveDelete-staff "BraceEnd"))
