;;;;;;;;;;CompareScores
(let ((staffnum #f)(message #f)(first #f)(second #f))
    (d-Open)
    (d-GoToPosition 1 1 1 1)
    (set! first (d-SelectTab))
    (d-NewWindow)
    (d-Open)
    (d-GoToPosition 1 1 1 1)
    (set! second (d-SelectTab))        
    (set! staffnum (1- (d-GetStaff)))
    (CheckTabs first second staffnum))
