;;; Emmentaler rests
(define REST0 "")
(define REST1 "")

(define REST2 "")
(define REST3 "")
(define REST4 "")
(define REST5 "")
(define REST6 "")
(define REST7 "")

(define Rest0  (string-append "\n" REST0 "\nemmentaler"))
(define Rest1  (string-append "\n" REST1 "\nemmentaler"))
(define Rest2  (string-append "\n" REST2 "\nemmentaler"))
(define Rest3  (string-append "\n" REST3 "\nemmentaler"))
(define Rest4  (string-append "\n" REST4 "\nemmentaler"))
(define Rest5  (string-append "\n" REST5 "\nemmentaler"))
(define Rest6  (string-append "\n" REST6 "\nemmentaler"))
(define Rest7  (string-append "\n" REST7 "\nemmentaler"))
(define Rests (vector Rest0 Rest1 Rest2 Rest3 Rest4 Rest5 Rest6 Rest7 ))

;;; Articulation Symbols
(define DENEMO_STACCATO "")
(define DENEMO_STACCATISSIMO "")
(define DENEMO_ACCENT  "")
(define DENEMO_MARCATO "")
(define DENEMO_TENUTO "")
(define DENEMO_UPBOW "")
(define DENEMO_DOWNBOW "")
(define DENEMO_HARMONIC "")
(define DENEMO_SNAPPIZZICATO "")
(define DENEMO_ARPEGGIATODOWN "\xF0\x9D\x86\x84")
(define DENEMO_ARPEGGIATOUP "\xF0\x9D\x86\x83")
(define DENEMO_PLUSNOTEHEAD "")
(define DENEMO_FERMATA "")

(define LG-Staccato (string-append "\n" DENEMO_STACCATO "\nemmentaler"))
(define LG-Staccatissimo (string-append "\n" DENEMO_STACCATISSIMO "\nemmentaler"))
(define LG-Accent (string-append "\n" DENEMO_ACCENT "\nemmentaler"))
(define LG-Marcato (string-append "\n" DENEMO_MARCATO "\nemmentaler"))
(define LG-Tenuto (string-append "\n" DENEMO_TENUTO "\nemmentaler"))
(define LG-UpBow (string-append "\n" DENEMO_UPBOW "\nemmentaler"))
(define LG-DownBow (string-append "\n" DENEMO_DOWNBOW "\nemmentaler"))
(define LG-Harmonic (string-append "\n" DENEMO_HARMONIC "\nemmentaler"))
(define LG-Snappizzicato (string-append "\n" DENEMO_SNAPPIZZICATO "\nemmentaler"))
(define LG-ArpeggiatoDown (string-append "\n" DENEMO_ARPEGGIATODOWN "\nemmentaler"))
(define LG-ArpeggiatoUp (string-append "\n" DENEMO_ARPEGGIATOUP "\nemmentaler"))
(define LG-PlusNoteHead (string-append "\n" DENEMO_PLUSNOTEHEAD "\nemmentaler"))
(define LG-Fermata (string-append "\n" DENEMO_FERMATA "\nemmentaler"))

