;;;; NewStructuredStaff
(let ()
(d-MoveToBeginning) 
(d-AddAfter)
(d-MoveToStaffUp)
(if (or (Timesignature?) (d-Directive-standalone? "Upbeat")(d-Directive-standalone? "ShortMeasure"))
        (begin
            (d-PushPosition)
            (d-UnsetMark)
            (d-SetMark)
            (d-Copy)
            (d-MoveToStaffDown)
            (d-Paste) 
            (d-PopPosition)))
(while (d-MoveCursorRight)
    (if (or (Timesignature?) (d-Directive-standalone? "Upbeat")(d-Directive-standalone? "ShortMeasure"))
        (begin
            (d-PushPosition)
            (d-UnsetMark)
            (d-SetMark)
            (d-Copy)
            (d-MoveToStaffDown)
            (d-Paste) 
            (d-PopPosition))))
(d-MoveToStaffDown)
(d-MoveToBeginning))
