/******** generated automatically from generate_source. See generate_source.c */
{"CursorLeft", NULL, N_("Cursor Left"), NULL,N_("Moves the cursor one object left, altering the selection if any"),G_CALLBACK (cursorleft_cb)},
{"CursorDown", NULL, N_("Cursor Down"), NULL,N_("Moves the cursor one scale step down"),G_CALLBACK (cursordown_cb)},
{"CursorUp", NULL, N_("Cursor Up"), NULL,N_("Moves the cursor one scale step up"),G_CALLBACK (cursorup_cb)},
{"CursorRight", NULL, N_("Cursor Right"), NULL,N_("Moves the cursor one object right, altering the selection if any"),G_CALLBACK (cursorright_cb)},
{"GoToMark", NULL, N_("To Mark"), NULL,N_("Moves the cursor to the Mark without altering the selection"),G_CALLBACK (goto_mark)},
{"StaffUp", NULL, N_("Staff Up"), NULL,N_("Moves the cursor to the staff above"),G_CALLBACK (staffup_cb)},
{"StaffDown", NULL, N_("Staff Down"), NULL,N_("Moves the cursor to the staff below"),G_CALLBACK (staffdown_cb)},
{"MeasureLeft", NULL, N_("Measure Left"), NULL,N_("Moves the cursor to the first object in the next measure"),G_CALLBACK (measureleft_cb)},
{"MeasureRight", NULL, N_("Measure Right"), NULL,N_("Moves the cursor to the first object in the previous measure"),G_CALLBACK (measureright_cb)},
{"A", NULL, N_("A"), NULL,N_("Action for note A (Insert, Edit or Move Cursor, depending on Mode)"),G_CALLBACK (go_to_A_key_cb)},
{"B", NULL, N_("B"), NULL,N_("Action for note B (Insert, Edit or Move Cursor, depending on Mode)"),G_CALLBACK (go_to_B_key_cb)},
{"C", NULL, N_("C"), NULL,N_("Action for note C (Insert, Edit or Move Cursor, depending on Mode)"),G_CALLBACK (go_to_C_key_cb)},
{"D", NULL, N_("D"), NULL,N_("Action for note D (Insert, Edit or Move Cursor, depending on Mode)"),G_CALLBACK (go_to_D_key_cb)},
{"E", NULL, N_("E"), NULL,N_("Action for note E (Insert, Edit or Move Cursor, depending on Mode)"),G_CALLBACK (go_to_E_key_cb)},
{"F", NULL, N_("F"), NULL,N_("Action for note F (Insert, Edit or Move Cursor, depending on Mode)"),G_CALLBACK (go_to_F_key_cb)},
{"G", NULL, N_("G"), NULL,N_("Action for note G (Insert, Edit or Move Cursor, depending on Mode)"),G_CALLBACK (go_to_G_key_cb)},
{"OctaveUp", NULL, N_("Octave Up"), NULL,N_("Octave Up"),G_CALLBACK (octave_up_key_cb)},
{"OctaveDown", NULL, N_("Octave Down"), NULL,N_("Octave Down"),G_CALLBACK (octave_down_key_cb)},
{"WholeNote", NULL, N_(""MUSIC_FONT("0")""), NULL,N_("Insert whole-note"),G_CALLBACK (insert_chord_0key_cb)},
{"HalfNote", NULL, N_(""MUSIC_FONT("1")""), NULL,N_("Insert half-note"),G_CALLBACK (insert_chord_1key_cb)},
{"QuarterNote", NULL, N_(""MUSIC_FONT("2")""), NULL,N_("Insert quarter-note"),G_CALLBACK (insert_chord_2key_cb)},
{"EighthNote", NULL, N_(""MUSIC_FONT("3")""), NULL,N_("Insert eighth-note"),G_CALLBACK (insert_chord_3key_cb)},
{"SixteenthNote", NULL, N_(""MUSIC_FONT("4")""), NULL,N_("Insert sixteenth-note"),G_CALLBACK (insert_chord_4key_cb)},
{"ThirtysecondNote", NULL, N_(""MUSIC_FONT("5")""), NULL,N_("Insert thirty-second-note"),G_CALLBACK (insert_chord_5key_cb)},
{"SixtyfourthNote", NULL, N_(""MUSIC_FONT("6")""), NULL,N_("Insert sixty-fourth-note"),G_CALLBACK (insert_chord_6key_cb)},
{"InsertBlankWholeNote", NULL, N_("Insert Blank Whole Note"), NULL,N_("No Tooltip yet"),G_CALLBACK (insert_blankchord_0key_cb)},
{"InsertBlankHalfNote", NULL, N_("Insert Blank Half Note"), NULL,N_("No Tooltip yet"),G_CALLBACK (insert_blankchord_1key_cb)},
{"InsertBlankQuarterNote", NULL, N_("Insert Blank Quarter Note"), NULL,N_("No Tooltip yet"),G_CALLBACK (insert_blankchord_2key_cb)},
{"InsertBlankEighthNote", NULL, N_("Insert Blank Eigth Note"), NULL,N_("No Tooltip yet"),G_CALLBACK (insert_blankchord_3key_cb)},
{"InsertBlankSixteenthNote", NULL, N_("Insert Blank Sixteenth Note"), NULL,N_("No Tooltip yet"),G_CALLBACK (insert_blankchord_4key_cb)},
{"InsertBlankThirtysecondNote", NULL, N_("Insert Blank Thirty Second Note"), NULL,N_("No Tooltip yet"),G_CALLBACK (insert_blankchord_5key_cb)},
{"InsertBlankSixtyfourthNote", NULL, N_("Insert Blank Sixty Forth Note"), NULL,N_("No Tooltip yet"),G_CALLBACK (insert_blankchord_6key_cb)},
{"ToggleRestMode", NULL, N_("Toggle Rest Mode"), NULL,N_("No Tooltip yet"),G_CALLBACK (rest_toggle_key_cb)},
{"ToggleBlankMode", NULL, N_("Toggle Blank Mode"), NULL,N_("No Tooltip yet"),G_CALLBACK (toggle_blank_cb)},
{"InsertWholeRest", NULL, N_(""MUSIC_FONT("r")""), NULL,N_("Insert whole-note rest"),G_CALLBACK (insert_rest_0key_cb)},
{"InsertHalfRest", NULL, N_(""MUSIC_FONT("s")""), NULL,N_("Insert half-note rest"),G_CALLBACK (insert_rest_1key_cb)},
{"InsertQuarterRest", NULL, N_(""MUSIC_FONT("t")""), NULL,N_("Insert quarter-note rest"),G_CALLBACK (insert_rest_2key_cb)},
{"InsertEighthRest", NULL, N_(""MUSIC_FONT("u")""), NULL,N_("Insert eighth-note rest"),G_CALLBACK (insert_rest_3key_cb)},
{"InsertSixteenthRest", NULL, N_(""MUSIC_FONT("v")""), NULL,N_("Insert sixteenth-note rest"),G_CALLBACK (insert_rest_4key_cb)},
{"InsertThirtysecondRest", NULL, N_(""MUSIC_FONT("w")""), NULL,N_("Insert thirty-second note rest"),G_CALLBACK (insert_rest_5key_cb)},
{"InsertSixtyfourthRest", NULL, N_(""MUSIC_FONT("x")""), NULL,N_("Insert sixty-fourth note rest"),G_CALLBACK (insert_rest_6key_cb)},
{"InsertDuplet", NULL, N_("Insert Duplet"), NULL,N_("No Tooltip yet"),G_CALLBACK (insert_duplet_cb)},
{"InsertTriplet", NULL, N_("Insert Triplet"), NULL,N_("No Tooltip yet"),G_CALLBACK (insert_triplet_cb)},
{"StartTriplet", NULL, N_("Start Triplet"), NULL,N_("No Tooltip yet"),G_CALLBACK (start_triplet_cb)},
{"EndTuplet", NULL, N_("End Tuplet"), NULL,N_("No Tooltip yet"),G_CALLBACK (end_tuplet_cb)},
{"InsertQuadtuplet", NULL, N_("Insert Quadtuplet"), NULL,N_("No Tooltip yet"),G_CALLBACK (insert_quadtuplet_cb)},
{"InsertQuintuplet", NULL, N_("Insert Quintuplet"), NULL,N_("No Tooltip yet"),G_CALLBACK (insert_quintuplet_cb)},
{"InsertSextuplet", NULL, N_("Insert Sextuplet"), NULL,N_("No Tooltip yet"),G_CALLBACK (insert_sextuplet_cb)},
{"InsertSeptuplet", NULL, N_("Insert Septuplet"), NULL,N_("No Tooltip yet"),G_CALLBACK (insert_septuplet_cb)},
{"AddNoteToChord", NULL, N_("Add note"), NULL,N_("Add a note to the current chord\nThe cursor position determines which note to add"),G_CALLBACK (add_tone_key_cb)},
{"RemoveNoteFromChord", NULL, N_("Remove note"), NULL,N_("Remove a note from the current chord"),G_CALLBACK (remove_tone_key_cb)},
{"Sharpen", NULL, N_("Sharpen"), NULL,N_("No Tooltip yet"),G_CALLBACK (sharpen_key_cb)},
{"Flatten", NULL, N_("Flatten"), NULL,N_("No Tooltip yet"),G_CALLBACK (flatten_key_cb)},
{"StemUp", NULL, N_("StemUp"), NULL,N_("Alters a StemNeutral object to stem up."),G_CALLBACK (stem_up_cb)},
{"StemDown", NULL, N_("StemDown"), NULL,N_("Alters a StemNeutral object to stem down."),G_CALLBACK (stem_down_cb)},
{"AddDot", NULL, N_("Add Dot"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_dot_key_cb)},
{"RemoveDot", NULL, N_("Remove Dot"), NULL,N_("No Tooltip yet"),G_CALLBACK (remove_dot_key_cb)},
{"InsertTiedNote", NULL, N_("Tied note"), NULL,N_("Inserts a duplicate of the current note, tied"),G_CALLBACK (tie_notes_key_cb)},
{"DeleteObject", NULL, N_("Delete Object"), NULL,N_("Delete the object at the cursor"),G_CALLBACK (deleteobject_cb)},
{"DeletePreviousObject", NULL, N_("Delete Previous Object"), NULL,N_("Delete to the left of the cursor."),G_CALLBACK (deletepreviousobject_cb)},
{"InsertMeasure", NULL, N_("Insert Measure"), NULL,N_("Insert a blank measure before the current one (in all staffs)"),G_CALLBACK (insert_measure_key_cb)},
{"AppendMeasure", NULL, N_("Append Measure"), NULL,N_("No Tooltip yet"),G_CALLBACK (append_measure_key_cb)},
{"DeleteMeasure", NULL, N_("Delete Measure"), NULL,N_("Delete the current measure in this staff, leaving the staff short"),G_CALLBACK (deletemeasure_cb)},
{"DeleteMeasureAllStaffs", NULL, N_("Delete Measure All Staffs"), NULL,N_("Delete the current measure in all staffs"),G_CALLBACK (deletemeasureallstaffs_cb)},
{"ShrinkMeasures", NULL, N_("Shrink Measure"), NULL,N_("No Tooltip yet"),G_CALLBACK (adjust_measure_less_width_key_cb)},
{"WidenMeasures", NULL, N_("Widen Measures"), NULL,N_("No Tooltip yet"),G_CALLBACK (adjust_measure_more_width_key_cb)},
{"ShorterStaffs", NULL, N_("Shorter Staffs"), NULL,N_("No Tooltip yet"),G_CALLBACK (adjust_staff_less_height_key_cb)},
{"TallerStaffs", NULL, N_("Taller Staffs"), NULL,N_("No Tooltip yet"),G_CALLBACK (adjust_staff_more_height_key_cb)},
{"InsertTrebleClef", NULL, N_("New Treble Clef"), NULL,N_("No Tooltip yet"),G_CALLBACK (newcleftreble_cb)},
{"InsertBassClef", NULL, N_("New Bass Clef"), NULL,N_("No Tooltip yet"),G_CALLBACK (newclefbass_cb)},
{"Insertg8clef", NULL, N_("New G8 Clef"), NULL,N_("No Tooltip yet"),G_CALLBACK (newclefg8_cb)},
{"InsertAltoClef", NULL, N_("New Alto Clef"), NULL,N_("No Tooltip yet"),G_CALLBACK (newclefalto_cb)},
{"InsertTenorClef", NULL, N_("New Tenor Clef"), NULL,N_("No Tooltip yet"),G_CALLBACK (newcleftenor_cb)},
{"InsertSopranoClef", NULL, N_("New Soprano Clef"), NULL,N_("No Tooltip yet"),G_CALLBACK (newclefsoprano_cb)},
{"SetInitialTrebleClef", NULL, N_("Set Treble Clef"), NULL,N_("No Tooltip yet"),G_CALLBACK (setcleftreble_cb)},
{"SetInitialBassClef", NULL, N_("Set Bass Clef"), NULL,N_("No Tooltip yet"),G_CALLBACK (setclefbass_cb)},
{"SetInitialg8clef", NULL, N_("Set G8 Clef"), NULL,N_("No Tooltip yet"),G_CALLBACK (setclefg8_cb)},
{"SetInitialAltoClef", NULL, N_("Set Alto Clef"), NULL,N_("No Tooltip yet"),G_CALLBACK (setclefalto_cb)},
{"SetInitialTenorClef", NULL, N_("Set Tenor Clef"), NULL,N_("No Tooltip yet"),G_CALLBACK (setcleftenor_cb)},
{"SetInitialSopranoClef", NULL, N_("Set Soprano Clef"), NULL,N_("No Tooltip yet"),G_CALLBACK (setclefsoprano_cb)},
{"Insert22Time", NULL, N_("Insert 2/2 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (newtimesig22_cb)},
{"Insert32Time", NULL, N_("Insert 3/2 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (newtimesig32_cb)},
{"Insert42Time", NULL, N_("Insert 4/2 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (newtimesig42_cb)},
{"Insert44Time", NULL, N_("Insert 4/4 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (newtimesig44_cb)},
{"Insert34Time", NULL, N_("Insert 3/4 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (newtimesig34_cb)},
{"Insert24Time", NULL, N_("Insert 2/4 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (newtimesig24_cb)},
{"Insert64Time", NULL, N_("Insert 6/4 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (newtimesig64_cb)},
{"Insert38Time", NULL, N_("Insert 3/8 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (newtimesig38_cb)},
{"Insert68Time", NULL, N_("Insert 6/8 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (newtimesig68_cb)},
{"Insert128Time", NULL, N_("Insert 12/8 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (newtimesig128_cb)},
{"Insert98Time", NULL, N_("Insert 9/8 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (newtimesig98_cb)},
{"Set22Time", NULL, N_("Set 2/2 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (settimesig22_cb)},
{"Set32Time", NULL, N_("Set 3/2 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (settimesig32_cb)},
{"Set42Time", NULL, N_("Set 4/2 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (settimesig42_cb)},
{"Set44Time", NULL, N_("Set 4/4 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (settimesig44_cb)},
{"Set34Time", NULL, N_("Set 3/4 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (settimesig34_cb)},
{"Set24Time", NULL, N_("Set 2/4 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (settimesig24_cb)},
{"Set64Time", NULL, N_("Set 6/4 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (settimesig64_cb)},
{"Set38Time", NULL, N_("Set 3/8 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (settimesig38_cb)},
{"Set68Time", NULL, N_("Set 6/8 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (settimesig68_cb)},
{"Set128Time", NULL, N_("Set 12/8 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (settimesig128_cb)},
{"Set98Time", NULL, N_("Set 9/8 Time"), NULL,N_("No Tooltip yet"),G_CALLBACK (settimesig98_cb)},
{"InsertCmaj", NULL, N_("Insert Cmaj"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigcmaj_cb)},
{"InsertGmaj", NULL, N_("Insert Gmaj"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysiggmaj_cb)},
{"InsertDmaj", NULL, N_("Insert Dmaj"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigdmaj_cb)},
{"InsertAmaj", NULL, N_("Insert Amaj"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigamaj_cb)},
{"InsertEmaj", NULL, N_("Insert Emaj"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigemaj_cb)},
{"InsertBmaj", NULL, N_("Insert Bmaj"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigbmaj_cb)},
{"InsertFSharpmaj", NULL, N_("Insert F# Major"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigfsharpmaj_cb)},
{"InsertCSharpmaj", NULL, N_("Insert C# Major"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigcsharpmaj_cb)},
{"InsertFmaj", NULL, N_("Insert F Major"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigfmaj_cb)},
{"InsertBflatmaj", NULL, N_("Insert Bb Major"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigbflatmaj_cb)},
{"InsertEflatmaj", NULL, N_("Insert Eb Major"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigeflatmaj_cb)},
{"InsertAflatmaj", NULL, N_("Insert Ab Major"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigaflatmaj_cb)},
{"InsertDflatmaj", NULL, N_("Insert Db Major"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigdflatmaj_cb)},
{"InsertGflatmaj", NULL, N_("Insert Gb Major"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysiggflatmaj_cb)},
{"InsertCflatmaj", NULL, N_("Insert Cb Major"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigcflatmaj_cb)},
{"InsertAmin", NULL, N_("Insert A Minor"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigamin_cb)},
{"InsertEmin", NULL, N_("Insert E Minor"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigemin_cb)},
{"InsertBmin", NULL, N_("Insert B Minor"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigbmin_cb)},
{"InsertFSharpmin", NULL, N_("Insert F# Minor"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigfsharpmin_cb)},
{"InsertCSharpmin", NULL, N_("Insert C# Minor"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigcsharpmin_cb)},
{"InsertGSharpmin", NULL, N_("Insert G# Minor"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysiggsharpmin_cb)},
{"InsertDSharpmin", NULL, N_("Insert D# Minor"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigdsharpmin_cb)},
{"InsertASharpmin", NULL, N_("Insert A# Minor"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigasharpmin_cb)},
{"InsertDmin", NULL, N_("Insert D Minor"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigdmin_cb)},
{"InsertGmin", NULL, N_("Insert G Minor"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysiggmin_cb)},
{"InsertCmin", NULL, N_("Insert C Minor"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigcmin_cb)},
{"InsertFmin", NULL, N_("Insert F Minor"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigfmin_cb)},
{"InsertBflatmin", NULL, N_("Insert Bb Minor"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigbflatmin_cb)},
{"InsertEflatmin", NULL, N_("Insert Eb Minor"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigeflatmin_cb)},
{"InsertAflatmin", NULL, N_("Insert Ab Minor"), NULL,N_("No Tooltip yet"),G_CALLBACK (newkeysigaflatmin_cb)},
{"SetInitialCmaj", NULL, N_("Set Initial Keysig to C Major"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigcmaj_cb)},
{"SetInitialGmaj", NULL, N_("Set Initial Keysig to G Major"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysiggmaj_cb)},
{"SetInitialDmaj", NULL, N_("Set D Major as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigdmaj_cb)},
{"SetInitialAmaj", NULL, N_("Set A Major as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigamaj_cb)},
{"SetInitialEmaj", NULL, N_("Set E Major as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigemaj_cb)},
{"SetInitialBmaj", NULL, N_("Set B Major as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigbmaj_cb)},
{"SetInitialFSharpmaj", NULL, N_("Set F# Major as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigfsharpmaj_cb)},
{"SetInitialCSharpmaj", NULL, N_("Set C# Major as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigcsharpmaj_cb)},
{"SetInitialFmaj", NULL, N_("Set F Major as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigfmaj_cb)},
{"SetInitialBflatmaj", NULL, N_("Set Bb Major as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigbflatmaj_cb)},
{"SetInitialEflatmaj", NULL, N_("Set Eb Major as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigeflatmaj_cb)},
{"SetInitialAflatmaj", NULL, N_("Set Ab Major as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigaflatmaj_cb)},
{"SetInitialDflatmaj", NULL, N_("Set Db Major as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigdflatmaj_cb)},
{"SetInitialGflatmaj", NULL, N_("Set Gb Major as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysiggflatmaj_cb)},
{"SetInitialCflatmaj", NULL, N_("Set Cb Major as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigcflatmaj_cb)},
{"SetInitialAmin", NULL, N_("Set A Minor as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigamin_cb)},
{"SetInitialEmin", NULL, N_("Set E Minor as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigemin_cb)},
{"SetInitialBmin", NULL, N_("Set B Minor as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigbmin_cb)},
{"SetInitialFSharpmin", NULL, N_("Set F# Minor as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigfsharpmin_cb)},
{"SetInitialCSharpmin", NULL, N_("Set C# Minor as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigcsharpmin_cb)},
{"SetInitialGSharpmin", NULL, N_("Set G# Minor as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysiggsharpmin_cb)},
{"SetInitialDSharpmin", NULL, N_("Set D# Minor as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigdsharpmin_cb)},
{"SetInitialASharpmin", NULL, N_("Set A# Minor as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigasharpmin_cb)},
{"SetInitialDmin", NULL, N_("Set D Minor as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigdmin_cb)},
{"SetInitialGmin", NULL, N_("Set G Minor as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysiggmin_cb)},
{"SetInitialCmin", NULL, N_("Set C Minor as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigcmin_cb)},
{"SetInitialFmin", NULL, N_("Set F Minor as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigfmin_cb)},
{"SetInitialBflatmin", NULL, N_("Set Bb Minor as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigbflatmin_cb)},
{"SetInitialEflatmin", NULL, N_("Set Eb Minor as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigeflatmin_cb)},
{"SetInitialAflatmin", NULL, N_("Set Ab Minor as Initial Keysig"), NULL,N_("No Tooltip yet"),G_CALLBACK (setkeysigaflatmin_cb)},
{"SetMark", NULL, N_("Set Mark"), NULL,N_("No Tooltip yet"),G_CALLBACK (set_mark_cb)},
{"UnsetMark", NULL, N_("Unset Mark"), NULL,N_("No Tooltip yet"),G_CALLBACK (unset_mark_cb)},
{"ToggleBeginSlur", NULL, N_("Begin Slur"), NULL,N_("Insert/delete begin slur on this note"),G_CALLBACK (toggle_begin_slur_cb)},
{"ToggleEndSlur", NULL, N_("End Slur"), NULL,N_("Insert/delete end slur on this note"),G_CALLBACK (toggle_end_slur_cb)},
{"ToggleStartCrescendo", NULL, N_("Start Crescendo"), NULL,N_("No Tooltip yet"),G_CALLBACK (toggle_start_crescendo_cb)},
{"ToggleEndCrescendo", NULL, N_("End Crescendo"), NULL,N_("No Tooltip yet"),G_CALLBACK (toggle_end_crescendo_cb)},
{"ToggleStartDiminuendo", NULL, N_("Start Diminuendo"), NULL,N_("No Tooltip yet"),G_CALLBACK (toggle_start_diminuendo_cb)},
{"ToggleEndDiminuendo", NULL, N_("End Diminuendo"), NULL,N_("No Tooltip yet"),G_CALLBACK (toggle_end_diminuendo_cb)},
{"ToggleAccent", NULL, N_("Accent (Off/On)"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_accent_cb)},
{"ToggleFermata", NULL, N_("Fermata (Off/On)"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_fermata_cb)},
{"ToggleStaccato", NULL, N_("Staccato (Off/On)"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_staccato_cb)},
{"ToggleTenuto", NULL, N_("Tenuto (Off/On)"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_tenuto_cb)},
{"ToggleTrill", NULL, N_("Trill  (Off/On"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_trill_cb)},
{"ToggleTurn", NULL, N_("Turn (Off/On)"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_turn_cb)},
{"ToggleMordent", NULL, N_("Mordent (Off/On)"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_mordent_cb)},
{"ToggleStaccatissimo", NULL, N_("Staccatissimo  (Off/On)"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_staccatissimo_cb)},
{"ToggleCoda", NULL, N_("Coda (Off/On)"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_coda_cb)},
{"ToggleFlageolet", NULL, N_("Flageolet  (Off/On)"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_flageolet_cb)},
{"ToggleOpen", NULL, N_("Open (Off/On)"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_open_cb)},
{"TogglePrallMordent", NULL, N_("Prall Mordent  (Off/On)"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_prallmordent_cb)},
{"TogglePrallPrall", NULL, N_("Prall Prall  (Off/On)"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_prallprall_cb)},
{"TogglePrall", NULL, N_("Prall (Off/On)"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_prall_cb)},
{"ToggleReverseTurn", NULL, N_("Reverse Turn  (Off/On)"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_reverseturn_cb)},
{"ToggleSegno", NULL, N_("Segno  (Off/On)"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_segno_cb)},
{"ToggleSforzato", NULL, N_("Sforzato  (Off/On)"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_sforzato_cb)},
{"ToggleStopped", NULL, N_("Stopped  (Off/On)"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_stopped_cb)},
{"ToggleThumb", NULL, N_("Thumb  (Off/On)"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_thumb_cb)},
{"ToggleUpprall", NULL, N_("Up Prall (Off/On)"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_upprall_cb)},
{"ToggleArpeggio", NULL, N_("Apreggio (Off/On)"), NULL,N_("No Tooltip yet"),G_CALLBACK (add_arpeggio_cb)},
{"SetGrace", NULL, N_("Set Grace"), NULL,N_("No Tooltip yet"),G_CALLBACK (set_grace_cb)},
{"ForceCaution", NULL, N_("Force Cautionary Accidental"), NULL,N_("No Tooltip yet"),G_CALLBACK (force_cautionary_cb)},
{"ChangePitch", NULL, N_("Change Pitch"), NULL,N_("No Tooltip yet"),G_CALLBACK (change_pitch_cb)},
{"DoubleBar", NULL, N_("Insert Double Bar"), NULL,N_("No Tooltip yet"),G_CALLBACK (insert_doublebar_cb)},
{"EndBar", NULL, N_("Insert Endbar"), NULL,N_("No Tooltip yet"),G_CALLBACK (insert_endbar_cb)},
{"OpenRepeat", NULL, N_("Insert Open Repeat"), NULL,N_("No Tooltip yet"),G_CALLBACK (insert_openrepeat_cb)},
{"CloseRepeat", NULL, N_("Insert Close Repeat"), NULL,N_("No Tooltip yet"),G_CALLBACK (insert_closerepeat_cb)},
{"OpenCloseRepeat", NULL, N_("Insert Open Close Repeat"), NULL,N_("No Tooltip yet"),G_CALLBACK (insert_opencloserepeat_cb)},
{"InsertRhythm", NULL, N_("Insert Rhythm"), NULL,N_("No Tooltip yet"),G_CALLBACK (insert_rhythm_pattern_cb)},
{"NextRhythm", NULL, N_("Next Rhythm"), NULL,N_("Make next rhythm pattern\nthe prevailing rhythm.\nNotes entered will follow this pattern"),G_CALLBACK (nextrhythm_cb)},
{"AppendMeasuresToScore", NULL, N_("Append Measure To Score"), NULL,N_("No Tooltip yet"),G_CALLBACK (append_measure_score_cb)},
{"FileMenu", NULL, N_("File"), NULL,N_("Creating, saving, loading, displaying and printing musical scores")},
{"Bookmarks", NULL, N_("Bookmarks"), NULL,N_("Creating, saving places in musical scores")},
{"ModeMenu", NULL, N_("Mode"), NULL,N_("Different keyboard and MIDI entry modes")},
{"EditMenu", NULL, N_("Edit"), NULL,N_("General editing commands")},
{"ViewMenu", NULL, N_("View"), NULL,N_("Control which tools are to be shown")},
{"StaffMenu", NULL, N_("Staffs/Voices"), NULL,N_("Staffs and voices")},
{"MovementMenu", NULL, N_("Movements"), NULL,N_("Movements in a score")},
{"HelpMenu", NULL, N_("Help"), NULL,N_("Help with denemo")},
{"InputMenu", NULL, N_("Input"), NULL,N_("input audio or midi")},
{"SharpenEnharmonicSet", NULL, N_("Shift Accidentals Sharpwise"), NULL,N_("Shifts the set of accidentals one step sharper"),G_CALLBACK (set_sharper)},
{"FlattenEnharmonicSet", NULL, N_("Shift Accidentals Flatwise"), NULL,N_("Shifts the set of accidentals one step flatter"),G_CALLBACK (set_flatter)},
{"PlaybackMenu", NULL, N_("Playback"), NULL,N_("Playing the music through midi file")},
{"New", GTK_STOCK_NEW, N_("New File"), NULL,N_("Start a new musical score"),G_CALLBACK (file_newwrapper)},
{"Open", GTK_STOCK_OPEN, N_("Open"), NULL,N_("Open a file containing a music score for editing"),G_CALLBACK (file_open_with_check)},
{"AddStaffs", GTK_STOCK_OPEN, N_("Add Staffs"), NULL,N_("Add staffs from a Denemo file"),G_CALLBACK (file_add_staffs)},
{"AddMovements", GTK_STOCK_OPEN, N_("Add Movement"), NULL,N_("Add movements from a Denemo file"),G_CALLBACK (file_add_movements)},
{"MovementProps", GTK_STOCK_PROPERTIES, N_("Change Properties"), NULL,N_("Change properties of this movement"),G_CALLBACK (movement_props_dialog)},
{"OpenNewWindow", GTK_STOCK_OPEN, N_("Open In New"), NULL,N_("Open a file containing a music score for editing in a separate working area (tab"),G_CALLBACK (openinnew)},
{"Save", GTK_STOCK_SAVE, N_("Save"), NULL,N_("Save the score"),G_CALLBACK (file_savewrapper)},
{"SaveAs", GTK_STOCK_SAVE_AS, N_("Save As"), NULL,N_("Save the score under a new name"),G_CALLBACK (file_saveaswrapper)},
{"OpenTemplate", GTK_STOCK_OPEN, N_("Open Template"), NULL,N_("Start a new score from a built-in template file"),G_CALLBACK (system_template_open_with_check)},
{"OpenExample", GTK_STOCK_OPEN, N_("Open Example"), NULL,N_("Start a new score from a built-in example"),G_CALLBACK (system_example_open_with_check)},
{"OpenMyTemplate", GTK_STOCK_OPEN, N_("Open custom template"), NULL,N_("Start a new score from one of your own template files"),G_CALLBACK (local_template_open_with_check)},
{"SaveTemplate", GTK_STOCK_SAVE_AS, N_("Save Template"), NULL,N_("Save the score as a template for re-use as a starting point for new scores"),G_CALLBACK (template_save)},
{"NewWindow", NULL, N_("New Tab"), NULL,N_("Create working area (tab with an empty score in it)"),G_CALLBACK (newview)},
{"InsertMovementBefore", NULL, N_("Insert Movement Before"), NULL,N_("Insert a new movement before the current one"),G_CALLBACK (insert_movement_before)},
{"InsertMovementAfter", NULL, N_("Insert Movement After"), NULL,N_("Insert a new movement after the current one"),G_CALLBACK (insert_movement_after)},
{"SaveParts", GTK_STOCK_SAVE_AS, N_("Save Parts"), NULL,N_("Save Parts: each staff becomes a file in lilypond format"),G_CALLBACK (file_savepartswrapper)},
{"ExportPDF", GTK_STOCK_SAVE_AS, N_("Export PDF"), NULL,N_("Export the score as a PDF document file"),G_CALLBACK (export_pdf_action)},
{"ConfigureScore", GTK_STOCK_PROPERTIES, N_("Score Wizard"), NULL,N_("Start up a wizard to create a new score. This allows you to set various properties of the score"),G_CALLBACK (scorewizard)},
{"PrintPreview", GTK_STOCK_PRINT_PREVIEW, N_("Print Preview"), NULL,N_("Displays the final finished score in your pdf viewer"),G_CALLBACK (printpreview_cb)},
{"PrintExcerptPreview", GTK_STOCK_PRINT_PREVIEW, N_("Print Excerpt"), NULL,N_("Displays a musical excerpt in your image viewer"),G_CALLBACK (printexcerptpreview_cb)},
{"Print", GTK_STOCK_PRINT, N_("Print"), NULL,N_("Displays the final finished score in a pdf viewer. From this you can print the file using the print command of the viewer"),G_CALLBACK (printall_cb)},
{"PrintPart", GTK_STOCK_PRINT, N_("Print Part"), NULL,N_("Displays the final finished score for the current part (that is current staff"),G_CALLBACK (printpart_cb)},
{"Close", GTK_STOCK_CLOSE, N_("Close Score"), NULL,N_("Close the current score. Other windows will stay open"),G_CALLBACK (close_gui_with_check)},
{"Quit", GTK_STOCK_QUIT, N_("Quit"), NULL,N_("Quit the Denemo program"),G_CALLBACK (closewrapper)},
{"Undo", GTK_STOCK_UNDO, N_("Undo"), NULL,N_("Undo"),G_CALLBACK (undowrapper)},
{"Redo", GTK_STOCK_REDO, N_("Redo"), NULL,N_("Redo"),G_CALLBACK (redowrapper)},
{"Select", NULL, N_("Select"), NULL,N_("Selecting stretches of notes")},
{"ExtendSelect", NULL, N_("Extend Selection"), NULL,N_("Extend the selection")},
{"Copy", GTK_STOCK_COPY, N_("Copy"), NULL,N_("Copy"),G_CALLBACK (copywrapper)},
{"Cut", GTK_STOCK_CUT, N_("Cut"), NULL,N_("Cut"),G_CALLBACK (cutwrapper)},
{"Paste", GTK_STOCK_PASTE, N_("Paste"), NULL,N_("Paste the selected music"),G_CALLBACK (pastewrapper)},
{"ScoreProperties", GTK_STOCK_PROPERTIES, N_("Score Properties"), NULL,N_("Change some of the properties of the current score. This will start up a dialog window"),G_CALLBACK (score_properties_dialog)},
{"SaveSelection", NULL, N_("Save Selection"), NULL,N_("Save the selected music. Not sure if this is working"),G_CALLBACK (saveselwrapper)},
{"Preferences", GTK_STOCK_PREFERENCES, N_("Change Preferences"), NULL,N_("Set and save your preferences for how Denemo operates on startup. Edit .denemo/denemorc for missing ones"),G_CALLBACK (preferences_change)},
{"KeyBindings", NULL, N_("Customize Commands, Shortcuts ..."), NULL,N_("Set actions to take in response to keypresses")},
{"SaveAccels", GTK_STOCK_SAVE, N_("Save Command Set"), NULL,N_("Save the current commands and keyboard shortcuts as the default"),G_CALLBACK (save_default_keymap_file_wrapper)},
{"CommandManagement", NULL, N_("Manage Command Set"), NULL,N_("View help, change and save keyboard shortcuts"),G_CALLBACK (configure_keyboard_dialog)},
{"LoadPlugins", NULL, N_("Load Plugins"), NULL,N_("Load Plugins"),G_CALLBACK (load_plugin)},
{"UnloadPlugins", NULL, N_("Unload Plugins"), NULL,N_("Unload Plugins"),G_CALLBACK (unloadplugins)},
{"ListPlugins", NULL, N_("List Plugins"), NULL,N_("List the loaded plugins"),G_CALLBACK (list_loaded_plugins)},
{"ListAvailablePlugins", NULL, N_("List Available Pluigins"), NULL,N_("List the available plugins"),G_CALLBACK (list_available_plugins)},
{"SwapStaffs", NULL, N_("Swap Staffs"), NULL,N_("Swap this staff with the one higher up. Note this actually swaps voices."),G_CALLBACK (swapstaffs)},
{"SplitVoices", NULL, N_("Split Voices"), NULL,N_("Split off the next voice as a separate staff"),G_CALLBACK (splitstaffs)},
{"JoinVoices", NULL, N_("Join Voices"), NULL,N_("Merge this staff as a voice on the previous staff"),G_CALLBACK (joinstaffs)},
{"SwapMovements", NULL, N_("Swap Movements"), NULL,N_("Swap this movement with the one before"),G_CALLBACK (swapmovements)},
{"VoiceUp", NULL, N_("Voice Up"), NULL,N_("Go to the higher numbered voice on staff"),G_CALLBACK (voiceup_cb)},
{"VoiceDown", NULL, N_("Voice Down"), NULL,N_("Go to the lower numbered voice on this staff"),G_CALLBACK (voicedown_cb)},
{"AddBefore", NULL, N_("Add Staff Before"), NULL,N_("Inserts a new staff before the current staff"),G_CALLBACK (newstaffbefore)},
{"AddAfter", NULL, N_("Add Staff After"), NULL,N_("Inserts/Adds a new staff after the current staff"),G_CALLBACK (dnm_newstaffafter)},
{"AddInitial", NULL, N_("Add Initial Staff"), NULL,N_("Inserts a new staff at the top of the score"),G_CALLBACK (newstaffinitial)},
{"AddLast", NULL, N_("Add Last Staff"), NULL,N_("Inserts a new staff at the end of the score"),G_CALLBACK (newstafflast)},
{"DeleteBefore", NULL, N_("Delete Staff Before"), NULL,N_("Deletes the staff before the current staff"),G_CALLBACK (delete_staff_before)},
{"DeleteStaff", NULL, N_("Delete Current Staff"), NULL,N_("Deletes the current staff"),G_CALLBACK (delete_staff_current)},
{"DeleteAfter", NULL, N_("Delete Staff After"), NULL,N_("Deletes the staff after the current staff"),G_CALLBACK (delete_staff_after)},
{"AddVoice", NULL, N_("Add Voice"), NULL,N_("Adds a new voice (part), to the current staff. It is tricky to switch between the voices. Suggest to use merge staffs"),G_CALLBACK (dnm_newstaffvoice)},
{"StaffProperties", GTK_STOCK_PROPERTIES, N_("Staff Properties"), NULL,N_("Change the properties of the current staff"),G_CALLBACK (staff_properties_change_cb)},
{"InsertMenu", NULL, N_("InsertMenu"), NULL,N_("Insert")},
{"Clef", NULL, N_("Clef"), NULL,N_("Clef")},
{"InitialClef", NULL, N_("Initial Clef"), NULL,N_("Change the initial clef of the current staff"),G_CALLBACK (clef_change_initial)},
{"InsertClef", NULL, N_("Clef Change"), NULL,N_("Insert a change of clef at the cursor"),G_CALLBACK (clef_change_insert)},
{"Key", NULL, N_("Keys"), NULL,N_("insert change key signature or set the initial key")},
{"InitialKey", NULL, N_("Initial Key"), NULL,N_("Set the initial key signature of the current staff"),G_CALLBACK (key_change_initial)},
{"InsertKey", NULL, N_("Insert Key Change"), NULL,N_("Insert a key change at the cursor position"),G_CALLBACK (key_change_insert)},
{"TimeSig", NULL, N_("Time Signatures"), NULL,N_("Manage the time signature changes and initial value")},
{"InitialTimeSig", NULL, N_("Inital Time Signature"), NULL,N_("Set the initial time signature of the current staff"),G_CALLBACK (timesig_change_initial)},
{"InsertTimeSig", NULL, N_("Insert Time Signature"), NULL,N_("Edit/Insert a time signature change for the current measure"),G_CALLBACK (timesig_change_insert)},
{"ChangeNotehead", NULL, N_("Set Notehead"), NULL,N_("Change the type of notehead for the current note"),G_CALLBACK (set_notehead)},
{"InsertStem", NULL, N_("Auto Stemming"), NULL,N_("Inserts a stem neutral object. After this automatic stem directions are active. You can click on this tag and use Sharpen/StemUp etc commands to change stem direction"),G_CALLBACK (stem_directive_insert)},
{"EditLyric", NULL, N_("Insert/Edit Lyric"), NULL,N_("Add a lyric to current note. Beware: all previous notes must have lyrics for printing correctly"),G_CALLBACK (lyric_insert)},
{"EditFiguredBass", NULL, N_("Insert/Edit Figured Bass"), NULL,N_("Add a bass figure to the current note. Use | sign to split the duration of a note so as to have multiple figures on one note. See Lilypond docs for other notation"),G_CALLBACK (figure_insert)},
{"EditChords", NULL, N_("Edit Chord Symbols"), NULL,N_("Allows chord symbols to be added to the current note. E.G.cis:dim7 for c-sharp diminished 7th. See Lilypond docs for notation"),G_CALLBACK (fakechord_insert)},
{"InsertDynamic", NULL, N_("Insert Dynamics"), NULL,N_("Inserts a dynamic marking at the cursor position"),G_CALLBACK (insert_dynamic)},
{"InsertLilyDirective", NULL, N_("Insert Lilypond"), NULL,N_("Insert or edit a directive in the LilyPond music typesetting language. This can be used for extra spacing, transposing or almost anything. See LilyPond documentation for ideas."),G_CALLBACK (lily_directive_insert)},
{"InsertLilyPostfix", NULL, N_("Postfix Lilypond"), NULL,N_("Insert or edit a LilyPond text to be post-fixed to the current note. This can be used for guitar fingerings, cautionary accidentals and much more. See LilyPond documentation."),G_CALLBACK (lily_directive_postfix)},
{"InsertBarline", NULL, N_("Insert Barline"), NULL,N_("Inserts specialized barline at the cursor position. Mostly not working"),G_CALLBACK (insert_barline)},
{"NavigationMenu", NULL, N_("Navigation"), NULL,N_("Getting around the score")},
{"GoToMeasure", NULL, N_("Go to Measure"), NULL,N_("Opens a dialog for going to a numbered measure"),G_CALLBACK (tomeasurenum)},
{"GoToBeginning", GTK_STOCK_GOTO_FIRST, N_("Go To Beginning"), NULL,N_("Go To Beginning"),G_CALLBACK (tohome)},
{"GoToEnd", GTK_STOCK_GOTO_LAST, N_("Go To End"), NULL,N_("Go To End"),G_CALLBACK (toend)},
{"NextMovement", NULL, N_("Next Movement"), NULL,N_("Go to the next movement"),G_CALLBACK (next_movement)},
{"PreviousMovement", NULL, N_("Previous Movement"), NULL,N_("Go to the previous movement"),G_CALLBACK (prev_movement)},
{"DeleteMovement", NULL, N_("Delete Movement"), NULL,N_("Delete the current movement"),G_CALLBACK (delete_movement)},
{"DeleteBookmarks", NULL, N_("Delete Bookmarks"), NULL,N_("Delete all bookmarks in current movement"),G_CALLBACK (deletebookmarks)},
{"Play", GTK_STOCK_MEDIA_PLAY, N_("Play"), NULL,N_("Play"),G_CALLBACK (ext_midi_playback)},
{"Stop", GTK_STOCK_MEDIA_STOP, N_("Stop"), NULL,N_("Stop"),G_CALLBACK (stop_midi_playback)},
{"PlayCSound", GTK_STOCK_MEDIA_PLAY, N_("Csound Playback"), NULL,N_("Play using CSound..."),G_CALLBACK (csoundplayback)},
{"PlaybackProperties", GTK_STOCK_PROPERTIES, N_("Playback Properties"), NULL,N_("Allows you to specify properties used in playing back (midi and csound"),G_CALLBACK (playback_properties_change)},
{"Help", NULL, N_("Browse Manual"), NULL,N_("Opens a browser on the user manual"),G_CALLBACK (browse_manual)},
{"About", NULL, N_("About"), NULL,N_("Gives the version number etc of this program"),G_CALLBACK (about)},
{"MoreMenu", NULL, N_("More"), NULL,N_("Allows choosing extra commands/menu items from disk")},
{"MoreCommands", NULL, N_("More Commands"), NULL,N_("Allows choosing standard extra commands/menu items"),G_CALLBACK (morecommands)},
{"MyCommands", NULL, N_("My Commands"), NULL,N_("Allows choosing extra commands/menu items from your own collection of extras"),G_CALLBACK (mycommands)},
{"AddBookmark", NULL, N_("Add Bookmark"), NULL,N_("Bookmark the current cursor position"),G_CALLBACK (addbookmark)},
{"GotoBookmark", NULL, N_("Goto Bookmarks"), NULL,N_("Go to a bookmarked point in the score"),G_CALLBACK (gotobookmark)},
{"NextBookmark", NULL, N_("Next Bookmark"), NULL,N_("Go to the next bookmarked point in the list"),G_CALLBACK (nextbookmark)},
{"PrevBookmark", NULL, N_("Prev Bookmark"), NULL,N_("Go to the previous bookmarked point in the list"),G_CALLBACK (prevbookmark)},
{"OpenRecent", GTK_STOCK_OPEN, N_("Open Recent"), NULL,N_("Open previously used files")},
{"ToggleEdit", NULL, N_("Toggle Edit Mode"), NULL,N_("Toggle between current mode and edit mode"),G_CALLBACK (toggle_edit_mode)},
{"ToggleRest", NULL, N_("Toggle Rest Mode"), NULL,N_("Toggle between note entry and rest entry"),G_CALLBACK (toggle_rest_mode)},
{"ToggleRhythm", NULL, N_("Toggle Rhythm Mode"), NULL,N_("Toggle between note entry and rhythm entry"),G_CALLBACK (toggle_rhythm_mode)},
{"ClearOverlay", NULL, N_("Clear Overlay"), NULL,N_("Clear the list of pitches that overlay the notes"),G_CALLBACK (clear_overlay)},
{"CreateRhythm", NULL, N_("Create Rhythm"), NULL,N_("Copy selection as a rhythm pattern for notes to follow as they are entered"),G_CALLBACK (create_rhythm_cb)},
{"DeleteRhythm", NULL, N_("Delete Rhythm"), NULL,N_("Delete the selected rhythm pattern"),G_CALLBACK (delete_rhythm_cb)},
{"ClassicModeNote", NULL, N_("Classic Mode"), NULL,N_("Moving the cursor and inserting notes or rests there")},
{"SelectNote", NULL, N_("Select Note"), NULL,N_("Moving the cursor to the nearest ...")},
{"InsertModeNote", NULL, N_("Insert"), NULL,N_("Actions for notes: inserting, deleting, etc.")},
{"StemControl", NULL, N_("Stem Direction"), NULL,N_("Actions to control the stem up/down")},
{"NoteheadControl", NULL, N_("Notehead Types"), NULL,N_("Different types of notehead")},
{"TiedNotes", NULL, N_("Tied Notes"), NULL,N_("Creating Tied Notes")},
{"DisplayEffects", NULL, N_("Display Effects"), NULL,N_("Effects that are only for the Denemo display,\nnot affecting the printed page.")},
{"Articulations", NULL, N_("Articulations"), NULL,N_("Articulations")},
{"Slurs", NULL, N_("Slurs"), NULL,N_("Slurs")},
{"GraceNotes", NULL, N_("Grace Notes"), NULL,N_("Grace Notes")},
{"Score", NULL, N_("Score"), NULL,N_("Score")},
{"Instruments", NULL, N_("Instruments"), NULL,N_("Instruments")},
{"Markings", NULL, N_("Markings"), NULL,N_("Markings")},
{"TextMarks", NULL, N_("Text/Symbol"), NULL,N_("Text and symbol Markings")},
{"StringedInstruments", NULL, N_("Strings"), NULL,N_("Commands for Stringed Instruments")},
{"InsertNote", NULL, N_("Note Entry"), NULL,N_("Inserting the note ...")},
{"AllOther", NULL, N_("Other"), NULL,N_("Anything not previously covered")},
{"Navigation", NULL, N_("Navigation"), NULL,N_("Moving around the piece")},
{"NoteEntry", NULL, N_("Note Entry"), NULL,N_("Entering notes")},
{"Articulation", NULL, N_("Articulation"), NULL,N_("Various expressive marks")},
{"Edit", NULL, N_("Edit"), NULL,N_("Editing")},
{"Measure", NULL, N_("Measure"), NULL,N_("Manipulating measures")},
{"Staff", NULL, N_("Staff"), NULL,N_("Commands for staffs")},
{"Playback", NULL, N_("Playback"), NULL,N_("Playing the music through midi file")},
{"SelectDuration", NULL, N_("Select Duration"), NULL,N_("Changing the prevailing duration or rhythm pattern")},
{"EditModeNote", NULL, N_("Edit"), NULL,N_("Appending, Changing, and deleting notes")},
{"EditNote", NULL, N_("Edit Note"), NULL,N_("Changing the note at the cursor to the nearest ...")},
{"EditDuration", NULL, N_("Edit Duration"), NULL,N_("Changing the duration of note at the cursor or appending a note of the given duration")},
{"Cursor", NULL, N_("Cursor"), NULL,N_("Moving the cursor")},
{"ClefMenu", NULL, N_("Clefs"), NULL,N_("Insert/change clef Set initial clef")},
{"ChordMenu", NULL, N_("Chords"), NULL,N_("Adding notes to make chords")},
{"MeasureMenu", NULL, N_("Measures"), NULL,N_("Measures: adding, deleting, navigating etc")},
{"Insert", NULL, N_("Insert"), NULL,N_("Inserting notes, measures, staffs, keysigs etc")},
{"InsertStaff", NULL, N_("Insert Staff"), NULL,N_("Insert a Staff relative to current staff")},
{"InsertMovement", NULL, N_("Insert Movement"), NULL,N_("Insert a Movement relative to current movement")},
{"InsertDuration", NULL, N_("Insert Duration"), NULL,N_("Inserting notes of a given duration")},
{"Change", NULL, N_("Change"), NULL,N_("Changing properties of notes, measures, staffs, keysigs etc")},
{"ModelessNote", NULL, N_("Notes/Durations"), NULL,N_("Modeless actions on notes/rests")},
{"NotesRests", NULL, N_("Notes/Rests"), NULL,N_("Actions for notes/rests")},
{"RestEntry", NULL, N_("Rest Entry"), NULL,N_("Modeless entry of rests")},
{"ChangeNote", NULL, N_("Change Note"), NULL,N_("Changing the note at the cursor to the nearest ...")},
{"ChangeDuration", NULL, N_("Change Duration"), NULL,N_("Changes the duration of the current note")},
{"ChangeRest", NULL, N_("Change Rest"), NULL,N_("Changes the duration of the current rest")},
{"ExpressionMarks", NULL, N_("Expression Marks"), NULL,N_("Dynamics, staccato, slurs, ties and other expressive marks")},
{"Markings", NULL, N_("Markings"), NULL,N_("Markings above and below the music")},
{"Dynamics", NULL, N_("Dynamics"), NULL,N_("Dynamic markings")},
{"Ornaments", NULL, N_("Ornaments"), NULL,N_("grace notes etc")},
{"Other", NULL, N_("Other"), NULL,N_("Lyrics, chord symbols, figured basses etc")},
{"Others", NULL, N_("Others"), NULL,N_("Less used actions")},
{"Favorites", NULL, N_("Favorites"), NULL,N_("Customized LilyPond inserts. Store often-used inserts here labelled with what they do")},
{"AddFavorite", NULL, N_("Add Favorite"), NULL,N_("Add a custom LilyPond insert to favorites menu")},
{"Tuplets", NULL, N_("Tuplets"), NULL,N_("Entering triplets and other tuplets")},
{"Delete", NULL, N_("Delete"), NULL,N_("Deleting notes, measures staffs keysigs etc")},
{"0", "NULL", N_(MUSIC_FONT("0")), NULL, N_("In insert mode, changes prevailing rhythm to "MUSIC_FONT("0")"\nIn edit mode changes the current note to "MUSIC_FONT("0")"\n or appends a "MUSIC_FONT("0")" if no current note\nIn classic mode inserts a "MUSIC_FONT("0")" at the cursor"),
G_CALLBACK (Dur0)},
{"Change0", "NULL", N_(MUSIC_FONT("0")), NULL, N_("Change current note to a "MUSIC_FONT("0")),
G_CALLBACK (ChangeDur0)},
{"ChangeRest0", NULL, N_("Change duration"), NULL, N_("Change durtion of current rest"),
G_CALLBACK (ChangeRest0)},
{"Insert0", NULL, N_("Insert a "MUSIC_FONT("0")""), NULL, N_("Inserts a "MUSIC_FONT("0")" at cursor position\nSets prevailing rhythm to "MUSIC_FONT("0")),
G_CALLBACK (InsertDur0)},
{"InsertRest0", NULL, N_("Insert a "MUSIC_FONT("0")"rest"), NULL, N_("Inserts a rest at cursor position\nSets prevailing rhythm to "MUSIC_FONT("0")),
G_CALLBACK (InsertRest0)},
{"1", "NULL", N_(MUSIC_FONT("1")), NULL, N_("In insert mode, changes prevailing rhythm to "MUSIC_FONT("1")"\nIn edit mode changes the current note to "MUSIC_FONT("1")"\n or appends a "MUSIC_FONT("1")" if no current note\nIn classic mode inserts a "MUSIC_FONT("1")" at the cursor"),
G_CALLBACK (Dur1)},
{"Change1", "NULL", N_(MUSIC_FONT("1")), NULL, N_("Change current note to a "MUSIC_FONT("1")),
G_CALLBACK (ChangeDur1)},
{"ChangeRest1", NULL, N_("Change duration"), NULL, N_("Change durtion of current rest"),
G_CALLBACK (ChangeRest1)},
{"Insert1", NULL, N_("Insert a "MUSIC_FONT("1")""), NULL, N_("Inserts a "MUSIC_FONT("1")" at cursor position\nSets prevailing rhythm to "MUSIC_FONT("1")),
G_CALLBACK (InsertDur1)},
{"InsertRest1", NULL, N_("Insert a "MUSIC_FONT("1")"rest"), NULL, N_("Inserts a rest at cursor position\nSets prevailing rhythm to "MUSIC_FONT("1")),
G_CALLBACK (InsertRest1)},
{"2", "NULL", N_(MUSIC_FONT("2")), NULL, N_("In insert mode, changes prevailing rhythm to "MUSIC_FONT("2")"\nIn edit mode changes the current note to "MUSIC_FONT("2")"\n or appends a "MUSIC_FONT("2")" if no current note\nIn classic mode inserts a "MUSIC_FONT("2")" at the cursor"),
G_CALLBACK (Dur2)},
{"Change2", "NULL", N_(MUSIC_FONT("2")), NULL, N_("Change current note to a "MUSIC_FONT("2")),
G_CALLBACK (ChangeDur2)},
{"ChangeRest2", NULL, N_("Change duration"), NULL, N_("Change durtion of current rest"),
G_CALLBACK (ChangeRest2)},
{"Insert2", NULL, N_("Insert a "MUSIC_FONT("2")""), NULL, N_("Inserts a "MUSIC_FONT("2")" at cursor position\nSets prevailing rhythm to "MUSIC_FONT("2")),
G_CALLBACK (InsertDur2)},
{"InsertRest2", NULL, N_("Insert a "MUSIC_FONT("2")"rest"), NULL, N_("Inserts a rest at cursor position\nSets prevailing rhythm to "MUSIC_FONT("2")),
G_CALLBACK (InsertRest2)},
{"3", "NULL", N_(MUSIC_FONT("3")), NULL, N_("In insert mode, changes prevailing rhythm to "MUSIC_FONT("3")"\nIn edit mode changes the current note to "MUSIC_FONT("3")"\n or appends a "MUSIC_FONT("3")" if no current note\nIn classic mode inserts a "MUSIC_FONT("3")" at the cursor"),
G_CALLBACK (Dur3)},
{"Change3", "NULL", N_(MUSIC_FONT("3")), NULL, N_("Change current note to a "MUSIC_FONT("3")),
G_CALLBACK (ChangeDur3)},
{"ChangeRest3", NULL, N_("Change duration"), NULL, N_("Change durtion of current rest"),
G_CALLBACK (ChangeRest3)},
{"Insert3", NULL, N_("Insert a "MUSIC_FONT("3")""), NULL, N_("Inserts a "MUSIC_FONT("3")" at cursor position\nSets prevailing rhythm to "MUSIC_FONT("3")),
G_CALLBACK (InsertDur3)},
{"InsertRest3", NULL, N_("Insert a "MUSIC_FONT("3")"rest"), NULL, N_("Inserts a rest at cursor position\nSets prevailing rhythm to "MUSIC_FONT("3")),
G_CALLBACK (InsertRest3)},
{"4", "NULL", N_(MUSIC_FONT("4")), NULL, N_("In insert mode, changes prevailing rhythm to "MUSIC_FONT("4")"\nIn edit mode changes the current note to "MUSIC_FONT("4")"\n or appends a "MUSIC_FONT("4")" if no current note\nIn classic mode inserts a "MUSIC_FONT("4")" at the cursor"),
G_CALLBACK (Dur4)},
{"Change4", "NULL", N_(MUSIC_FONT("4")), NULL, N_("Change current note to a "MUSIC_FONT("4")),
G_CALLBACK (ChangeDur4)},
{"ChangeRest4", NULL, N_("Change duration"), NULL, N_("Change durtion of current rest"),
G_CALLBACK (ChangeRest4)},
{"Insert4", NULL, N_("Insert a "MUSIC_FONT("4")""), NULL, N_("Inserts a "MUSIC_FONT("4")" at cursor position\nSets prevailing rhythm to "MUSIC_FONT("4")),
G_CALLBACK (InsertDur4)},
{"InsertRest4", NULL, N_("Insert a "MUSIC_FONT("4")"rest"), NULL, N_("Inserts a rest at cursor position\nSets prevailing rhythm to "MUSIC_FONT("4")),
G_CALLBACK (InsertRest4)},
{"5", "NULL", N_(MUSIC_FONT("5")), NULL, N_("In insert mode, changes prevailing rhythm to "MUSIC_FONT("5")"\nIn edit mode changes the current note to "MUSIC_FONT("5")"\n or appends a "MUSIC_FONT("5")" if no current note\nIn classic mode inserts a "MUSIC_FONT("5")" at the cursor"),
G_CALLBACK (Dur5)},
{"Change5", "NULL", N_(MUSIC_FONT("5")), NULL, N_("Change current note to a "MUSIC_FONT("5")),
G_CALLBACK (ChangeDur5)},
{"ChangeRest5", NULL, N_("Change duration"), NULL, N_("Change durtion of current rest"),
G_CALLBACK (ChangeRest5)},
{"Insert5", NULL, N_("Insert a "MUSIC_FONT("5")""), NULL, N_("Inserts a "MUSIC_FONT("5")" at cursor position\nSets prevailing rhythm to "MUSIC_FONT("5")),
G_CALLBACK (InsertDur5)},
{"InsertRest5", NULL, N_("Insert a "MUSIC_FONT("5")"rest"), NULL, N_("Inserts a rest at cursor position\nSets prevailing rhythm to "MUSIC_FONT("5")),
G_CALLBACK (InsertRest5)},
{"6", "NULL", N_(MUSIC_FONT("6")), NULL, N_("In insert mode, changes prevailing rhythm to "MUSIC_FONT("6")"\nIn edit mode changes the current note to "MUSIC_FONT("6")"\n or appends a "MUSIC_FONT("6")" if no current note\nIn classic mode inserts a "MUSIC_FONT("6")" at the cursor"),
G_CALLBACK (Dur6)},
{"Change6", "NULL", N_(MUSIC_FONT("6")), NULL, N_("Change current note to a "MUSIC_FONT("6")),
G_CALLBACK (ChangeDur6)},
{"ChangeRest6", NULL, N_("Change duration"), NULL, N_("Change durtion of current rest"),
G_CALLBACK (ChangeRest6)},
{"Insert6", NULL, N_("Insert a "MUSIC_FONT("6")""), NULL, N_("Inserts a "MUSIC_FONT("6")" at cursor position\nSets prevailing rhythm to "MUSIC_FONT("6")),
G_CALLBACK (InsertDur6)},
{"InsertRest6", NULL, N_("Insert a "MUSIC_FONT("6")"rest"), NULL, N_("Inserts a rest at cursor position\nSets prevailing rhythm to "MUSIC_FONT("6")),
G_CALLBACK (InsertRest6)},
 {"InsertA", NULL, N_("Insert A"), NULL, N_("Inserts note A before note at cursor\nCursor determines which octave\nNote is inserted in the prevailing rhythm"),
  G_CALLBACK (InsertA)},
  {"ChangeToA", NULL, N_("Change current note to A"), NULL, N_("Changes current note to the A nearest cursor or (if no current note) inserts the note A\nCursor determines which octave\nNote is inserted in the prevailing rhythm"),
   G_CALLBACK (ChangeToA)},
 {"InsertB", NULL, N_("Insert B"), NULL, N_("Inserts note B before note at cursor\nCursor determines which octave\nNote is inserted in the prevailing rhythm"),
  G_CALLBACK (InsertB)},
  {"ChangeToB", NULL, N_("Change current note to B"), NULL, N_("Changes current note to the B nearest cursor or (if no current note) inserts the note B\nCursor determines which octave\nNote is inserted in the prevailing rhythm"),
   G_CALLBACK (ChangeToB)},
 {"InsertC", NULL, N_("Insert C"), NULL, N_("Inserts note C before note at cursor\nCursor determines which octave\nNote is inserted in the prevailing rhythm"),
  G_CALLBACK (InsertC)},
  {"ChangeToC", NULL, N_("Change current note to C"), NULL, N_("Changes current note to the C nearest cursor or (if no current note) inserts the note C\nCursor determines which octave\nNote is inserted in the prevailing rhythm"),
   G_CALLBACK (ChangeToC)},
 {"InsertD", NULL, N_("Insert D"), NULL, N_("Inserts note D before note at cursor\nCursor determines which octave\nNote is inserted in the prevailing rhythm"),
  G_CALLBACK (InsertD)},
  {"ChangeToD", NULL, N_("Change current note to D"), NULL, N_("Changes current note to the D nearest cursor or (if no current note) inserts the note D\nCursor determines which octave\nNote is inserted in the prevailing rhythm"),
   G_CALLBACK (ChangeToD)},
 {"InsertE", NULL, N_("Insert E"), NULL, N_("Inserts note E before note at cursor\nCursor determines which octave\nNote is inserted in the prevailing rhythm"),
  G_CALLBACK (InsertE)},
  {"ChangeToE", NULL, N_("Change current note to E"), NULL, N_("Changes current note to the E nearest cursor or (if no current note) inserts the note E\nCursor determines which octave\nNote is inserted in the prevailing rhythm"),
   G_CALLBACK (ChangeToE)},
 {"InsertF", NULL, N_("Insert F"), NULL, N_("Inserts note F before note at cursor\nCursor determines which octave\nNote is inserted in the prevailing rhythm"),
  G_CALLBACK (InsertF)},
  {"ChangeToF", NULL, N_("Change current note to F"), NULL, N_("Changes current note to the F nearest cursor or (if no current note) inserts the note F\nCursor determines which octave\nNote is inserted in the prevailing rhythm"),
   G_CALLBACK (ChangeToF)},
 {"InsertG", NULL, N_("Insert G"), NULL, N_("Inserts note G before note at cursor\nCursor determines which octave\nNote is inserted in the prevailing rhythm"),
  G_CALLBACK (InsertG)},
  {"ChangeToG", NULL, N_("Change current note to G"), NULL, N_("Changes current note to the G nearest cursor or (if no current note) inserts the note G\nCursor determines which octave\nNote is inserted in the prevailing rhythm"),
   G_CALLBACK (ChangeToG)},
