;;;ConvertToWholeMeasureRests
(d-PushPosition)
(let ()
 (define (do-one)
	(if (and (Rest?) (not (d-Directive-chord? "WholeMeasureRest")))
       			(let ((measuredur (duration::GetWholeMeasureInTicks))
       				(this (d-GetDurationInTicks)))
		            (if (eq? this measuredur)
		                (begin
		                    (d-DeleteObject)
		                    (d-WholeMeasureRest))))))
  (define (do-staff)
      (d-MoveToBeginning)
      (do-one)
       (while (d-NextObject)
       		(do-one)))
  (define (do-movement)
    (while (d-StaffUp))
    (do-staff)
    (while (d-StaffDown)
        (do-staff)))
  (while (d-PreviousMovement))
  (do-movement)
  (while (d-NextMovement)
        (do-movement)))
(d-PopPosition)