;;;WholeMeasureSpacer
(if (not (None?))
	(while (not (Appending?))
    		(d-MoveCursorRight)))
(if (not (None?))
	(d-InsertMeasureAfter))
(d-InsertWholeMeasureRest)
(d-MoveCursorLeft)
(d-SetNonprinting)
(set! DenemoWholeMeasureRestParams "edit")
(d-WholeMeasureRest)
(if (not (Appending?))
	(d-MoveCursorRight))
(d-NoBarline)